### ISSUE TITLE
how can I use the midi in port for other tasks at the same time?

### ISSUE THREAD

**Issue by moebiussurfing** [roymacdonald/ofxParameterMidiSync#1]
Hey alo @roymacdonald 
,
I am controlling some sliders and toggles with my usb keyboard controller fine. thanks for this!
I am not sure if the addon is detecting midi notes to control toggles too, but anyway I only need the notes to trig events, no need to be reflected in ofxGui.

I tryed to add the notes like this but is not detecting nothing:
```
sync.linkMidiToOfParameter(89, CURVE_ZEBRA_ccParam);
sync.linkMidiToOfParameter(90, CURVE_NEGATIVE_ccParam);

ofxMidiMessage myMidiMessage;
myMidiMessage.pitch = 48;
//myMidiMessage.velocity = 127;
myMidiMessage.status = MIDI_NOTE_ON;
sync.linkMidiToOfParameter(myMidiMessage, NOTE_1_toggleParam);
```

I would like to add a listener or to build any way to get the input notes too, like when using the midi in example without the addon:
```
midiIn.addListener(this); //...
class ofApp : public ofBaseApp, public ofxMidiListener { }  //...
void ofApp::newMidiMessage(ofxMidiMessage& msg) { ]  //...
```

I don't know how to mix the addon with a normal use of the same midi input port.
I am using a previous commit, the one from 2015 because I still using 0.9.8 VS...

**Comment by roymacdonald** [comment]
Hi, 
well I think I did a lot of improvements recently so I would encourage you to give it a try at least. It might work with 0.9.8.

This addon only uses CC MIDI messages not notes so it would not work with the snippet of code you posted. Not at least as how you want it to.

So the `ofxParameterMidiSync` class is behaving as the listener as when you use the ofxMidi example.
in it there is a `newMidiMessage` which you can modify in order to make it work with notes, or the other solution is to add a different listener, which would be much tidier. So in ofxParameterMidiSync.h move the `ofxMidiIn midiIn;` line so it is public.
Then just use the code of the ofxMidi example but dont declare in ofApp an ofxMidiIn object. Use the one inside `ofxParameterMidiSync`.

So if you take the this addons example, modify the ofApp in the following way.

```cpp
#pragma once

#include "ofMain.h"

#include "ofxGui.h"
#include "ofxParameterMidiSync.h"

class ofApp : public ofBaseApp, public ofxMidiListener {// I changed this line
	
public:
	
	......// all the other stuff in your app.


     // Add this function which will be receiving new midi messages.
	void newMidiMessage(ofxMidiMessage& eventArgs);

    
    ofxParameterMidiSync sync;
   
};
```

In the ofApp.cpp

```cpp
void ofApp::setup() {
// all the other stuff in you might have in the setup. 
	
	// add this line. Add it after the line that read sync.setup(0, gui.getParameter());
	sync.midiIn.addListener(this);

}

void ofApp::newMidiMessage(ofxMidiMessage& msg) {
//Implement this function how ever you want to.

}

```

That would be all. Hope this helps.
cheers

**Comment by moebiussurfing** [comment]
Thanks a lot @roymacdonald !
 it worked perfect moving ofxMidiIn midiIn to public in your class with
sync.midiIn.addListener(this);
I can use the newMidiMessage listener in ofApp like on the midi input example.
If I use the listener from inside your class I would not knew how to modify "external variables from ofApp".

I tried a more recent commit but there's lot of errors related to glm vectors and some xml...
I ll try to jump to 0.10.0 soon, but I am using some not updated old addons ... I do not know if it's or why worth it.

**Comment by roymacdonald** [comment]
great to know. 
That should be the most straight forwards way of using it.
I was thinking that that kind of errors would happen. 
cheers
